"""
Django settings for django_support project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path


"""
    Locations of key files and directories for the IncomingShipments/HBL tracker
"""
class HBLdFiles:
    DB_MAIN_DIR = 'W:\\Logistics\\db'
    DB_MAIN = f'{DB_MAIN_DIR}\\hbl.sqlite'

    MED_DIR = f'{DB_MAIN_DIR}\\media'
    STATC_DIR = f'{DB_MAIN_DIR}\\static'

sysver_key = 'DEV'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$kx79q99%#u#r8taa4x5_3uiym24a5b=ri6wn9zq7czt7^kd8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost'
    ]

INTERNAL_IPS = [
    '127.0.0.1',
]

DATE_INPUT_FORMATS = [
    '%m/%d/%Y',
    '%Y-%m-%d',
    ]
DATE_FORMAT = 'Y-m-d'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # tools
    # 'widget_tweaks',
    # 'mathematical_expressions_parser',
    # this application
    'cMenu',
    # 'userprofiles',
    'incShip',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_support.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'string_if_invalid': 'Calvin is confused',
        },
    },
]

WSGI_APPLICATION = 'django_support.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'prod': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': HBLdFiles.DB_MAIN,
    },
    'dev-home': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': HBLdFiles.DB_MAIN,
    },
}
DATABASES['default']=DATABASES['dev-home']

MEDIA_ROOT = HBLdFiles.MED_DIR

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = HBLdFiles.STATC_DIR
STATICFILES_DIRS = [
    HBLdFiles.STATC_DIR,
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

